//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AziaFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public int TypeDishesid { get; set; }
        public string CostPrice { get; set; }
        public string Stoplist { get; set; }
    
        public virtual TypeDishes TypeDishes { get; set; }
    }
}
