//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DataRelize { get; set; }
        public int Genreid { get; set; }
        public string PushkinCard { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
